apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/murughan1985/knative-serving-helloworld:v1
          env:
            - name: TARGET
              value: "Knative"