apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-sample
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/murughan1985/knative-eventing-sample:v1